### ISSUE TITLE
UnicodeDecodeError after submit "preparation done, apply desired effects on the images" section

### ISSUE THREAD

**Issue by IzumiSatoshi** [nicolai256/Few-Shot-Patch-Based-Training#3]
Every time after submit "preparation done, apply desired effects on the images" section, this error occurs.  
Environment : Windows10 and anaconda python 3.9  
thanks
```
(python_3_9) PS C:\Users\81809\Desktop\Projects\nicolai_fewshot\Few-Shot-Patch-Based-Training> python _tools\fewshot_UI.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\81809\anaconda3\envs\python_3_9\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\81809\anaconda3\envs\python_3_9\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\81809\anaconda3\envs\python_3_9\lib\site-packages\gooey\gui\processor.py", line 70, in _forward_stdout
    _progress = self._extract_progress(line)
  File "C:\Users\81809\anaconda3\envs\python_3_9\lib\site-packages\gooey\gui\processor.py", line 84, in _extract_progress
    find = partial(re.search, string=text.strip().decode(self.encoding))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 10: invalid start byte
```

**Comment by IzumiSatoshi** [comment]
ah, one more important thing to note.
I change requirements.txt file to like this and did pip install -r requirements.txt on conda.
Default requirements.txt didn't work because of syntax errors and not found responses. I have no idea about that.
```
ruamel.yaml
pysimplegui
Gooey
opencv-python
scikit-build
cython
Pillow
PyYAML==5.4
scikit-image==0.18.1
scipy==1.6.2
tensorflow==2.7.0
torch==1.9.0
torchvision==0.10.0
torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html  
numpy==1.21.2
moviepy
numba
```

**Comment by IzumiSatoshi** [comment]
I added print() before partial()
```
print(text.strip())
print(self.encoding)
find = partial(re.search, string=text.strip().decode(self.encoding))
```
and it says:
```
b"'disflow' \x82\xcd\x81A\x93\xe0\x95\x94\x83R\x83}\x83\x93\x83h\x82\xdc\x82\xbd\x82\xcd\x8aO\x95\x94\x83R\x83}\x83\x93\x83h\x81A"
utf-8
```

**Comment by epstomai** [comment]
i figured it out, you missed to put those [PATH](https://github.com/nicolai256/Few-Shot-Patch-Based-Training#put-these-into-path-system-variables) to system variables. 

i remembered i already finished config path, but it seems disappeared somehow.
and now FSPBT works smoothly.

**Comment by IzumiSatoshi** [comment]
> i figured it out, you missed to put those [PATH](https://github.com/nicolai256/Few-Shot-Patch-Based-Training#put-these-into-path-system-variables) to system variables.
> 
> i remembered i already finished config path, but it seems disappeared somehow. and now FSPBT works smoothly.

Thank you, pip install went perfectly! I didn't set PATH correctly.
However, the same error seems to keep occurring. In your case, did setting the PATH stop the UnicodeDecodeError from occurring?

**Comment by IzumiSatoshi** [comment]
wait, I didn't install Magick lol.
It is main reason I assume.
If so, I'm so sorry for take your time.

**Comment by epstomai** [comment]
"\x82\xcd\x81A\x93\xe0\x95\x94\..." means "is not recognized as an internal or external command, operable program or batch file", a common error you can always see in CMD. So, in my case, "disflow" isn't recognized as a program. Fixed my PATH, restart PowerShell and problem solved.

**Comment by IzumiSatoshi** [comment]
Thank you so much!!
I really appreciate your suggestion.
It seems to be working fine, maybe the problem was that I forgot to restart vscode.
I don't have time to train today, so I don't know if it will work all the way through, but I will close the issue now that the error in question has been resolved.
Thanks for sticking with me.
